# Generated by Django 5.2.8 on 2025-11-07 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(default='Norway', max_length=100)),
                ('annual_turnover', models.DecimalField(decimal_places=2, help_text='Annual turnover in EUR', max_digits=15)),
                ('esg_score', models.FloatField(default=50.0, help_text='ESG Score (0-100)')),
                ('baseline_emissions', models.DecimalField(blank=True, decimal_places=2, help_text='Baseline emissions in kg CO2', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deadline_date', models.DateField()),
                ('regulation', models.CharField(default='CSRD', max_length=100)),
                ('description', models.TextField()),
                ('applicable_to', models.CharField(default='All Nordic Companies', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['deadline_date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('EV_SOLAR', 'Electric - Solar'), ('EV_NUCLEAR', 'Electric - Nuclear'), ('EV_GRID', 'Electric - Grid Mix'), ('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], max_length=20)),
                ('capacity_tonnes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registration_year', models.IntegerField(default=2020)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'ordering': ['vehicle_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DEADLINE', 'Deadline Approaching'), ('ANOMALY', 'Emission Anomaly'), ('THRESHOLD', 'Threshold Exceeded'), ('ESG_SCORE', 'ESG Score Warning')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['company', 'resolved'], name='api_complia_company_d5dc66_idx'), models.Index(fields=['alert_type', 'severity'], name='api_complia_alert_t_8491a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_tonnes', models.DecimalField(decimal_places=2, max_digits=6)),
                ('emissions_kg_co2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('invoice_source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
            options={
                'ordering': ['-trip_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'trip_date'], name='api_deliver_company_fa8fcc_idx'), models.Index(fields=['is_anomaly'], name='api_deliver_is_anom_950307_idx')],
            },
        ),
    ]
