# Generated by Django 5.2.8 on 2025-11-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionDataLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_batch', models.JSONField(help_text='Raw emission data batch')),
                ('record_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='API', max_length=100)),
                ('batch_metadata', models.JSONField(blank=True, help_text='Batch processing info', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['company', 'uploaded_at'], name='api_emissio_company_2ad67e_idx')],
            },
        ),
    ]
